version: '3.9'

services:
  database:
    image: postgres:17-alpine
    container_name: datascience-piscine-database
    restart: always
    shm_size: 1024mb
    volumes:
      - ./ds00:/usr/src/app/ds00
      - ./ds01:/usr/src/app/ds01
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  
  jupyter:
    image: quay.io/jupyter/base-notebook
    container_name: datascience-piscine-jupyter
    restart: always
    volumes:
      - ./ds02:/home/jovyan/work/ds02
    ports:
      - 8888:8888


  pgadmin4:
    container_name: datascience-piscine-pgadmin4
    image: dpage/pgadmin4:9.2
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    restart: always
    ports:
      - 8000:80