version: '3.9'

services:
  database:
    image: postgres:17-alpine
    container_name: datascience-piscine-database
    restart: always
    shm_size: 128mb
    volumes:
      - ./ds00:/usr/src/app/ds00
      - ./ds01:/usr/src/app/ds01
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  pgadmin4:
    container_name: datascience-piscine-pgadmin4
    image: dpage/pgadmin4:9.2
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    restart: always
    ports:
      - 8000:80