version: '3.9'

services:
  database:
    image: postgres:17-alpine
    container_name: datascience-piscine-database
    restart: always
    shm_size: 1024mb
    volumes:
      - ./ds00:/usr/src/app/ds00
      - ./ds01:/usr/src/app/ds01
      - ./ds03:/usr/src/app/ds03
      - ./scripts:/usr/src/app/scripts
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  
  jupyter:
    image: quay.io/jupyter/base-notebook
    container_name: datascience-piscine-jupyter
    restart: always
    volumes:
      - ./ds02:/home/jovyan/work/ds02
      - ./ds03:/home/jovyan/work/ds03
      - ./scripts:/home/jovyan/scripts
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    command: start-notebook.sh --NotebookApp.notebook_dir=/home/jovyan/work/

  pgadmin4:
    container_name: datascience-piscine-pgadmin4
    image: dpage/pgadmin4:9.2
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    restart: always
    ports:
      - 8000:80